/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Workspace } from "./Workspace";
import { WorkspaceCountArgs } from "./WorkspaceCountArgs";
import { WorkspaceFindManyArgs } from "./WorkspaceFindManyArgs";
import { WorkspaceFindUniqueArgs } from "./WorkspaceFindUniqueArgs";
import { CreateWorkspaceArgs } from "./CreateWorkspaceArgs";
import { UpdateWorkspaceArgs } from "./UpdateWorkspaceArgs";
import { DeleteWorkspaceArgs } from "./DeleteWorkspaceArgs";
import { PageFindManyArgs } from "../../page/base/PageFindManyArgs";
import { Page } from "../../page/base/Page";
import { WorkspaceService } from "../workspace.service";
@graphql.Resolver(() => Workspace)
export class WorkspaceResolverBase {
  constructor(protected readonly service: WorkspaceService) {}

  async _workspacesMeta(
    @graphql.Args() args: WorkspaceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Workspace])
  async workspaces(
    @graphql.Args() args: WorkspaceFindManyArgs
  ): Promise<Workspace[]> {
    return this.service.workspaces(args);
  }

  @graphql.Query(() => Workspace, { nullable: true })
  async workspace(
    @graphql.Args() args: WorkspaceFindUniqueArgs
  ): Promise<Workspace | null> {
    const result = await this.service.workspace(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Workspace)
  async createWorkspace(
    @graphql.Args() args: CreateWorkspaceArgs
  ): Promise<Workspace> {
    return await this.service.createWorkspace({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Workspace)
  async updateWorkspace(
    @graphql.Args() args: UpdateWorkspaceArgs
  ): Promise<Workspace | null> {
    try {
      return await this.service.updateWorkspace({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Workspace)
  async deleteWorkspace(
    @graphql.Args() args: DeleteWorkspaceArgs
  ): Promise<Workspace | null> {
    try {
      return await this.service.deleteWorkspace(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Page], { name: "pages" })
  async findPages(
    @graphql.Parent() parent: Workspace,
    @graphql.Args() args: PageFindManyArgs
  ): Promise<Page[]> {
    const results = await this.service.findPages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
